# BUILD
cc_test(
    name = "rocket_test",
    srcs = ["RocketTest.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//:water_rocket_library",
    ],
)